<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Course Code' => 'Code de cours',
    'View Details' => 'Voir les détails',
    '\'Are you sure you want to delete this item?' => 'Êtes-vous sûr de bien vouloir supprimer cet élément?',
    'All Registered Courses' => 'Tous les cours enregistrés',
    'Are you sure you want to delete this item?' => 'Êtes-vous sûr de bien vouloir supprimer cet élément?',
    'Back' => 'Arrière',
    'Bio' => 'Bio',
    'Class' => 'Classe',
    'Code' => 'Code',
    'Course' => 'Cours',
    'Course Field' => 'Champs de cours',
    'Course Fields' => 'Champs de cours',
    'Courses' => 'Cours',
    'Create Course' => 'Créer un cours',
    'Create Course Field' => 'Créer un cours terrain',
    'Create Instructor' => 'Créer instructeur',
    'Create Schedule' => 'Créer un calendrier',
    'Create Semester' => 'Créer semestre',
    'Create Student' => 'Créer des étudiants',
    'Create Time Slot' => 'Créer Créneau',
    'Created At' => 'Créé à',
    'Created By' => 'Créé par',
    'Dashboard' => 'Tableau de bord',
    'Delete' => 'Effacer',
    'Enter email' => 'Entrez email',
    'Enter password' => 'Entrer le mot de passe',
    'Field' => 'Champ',
    'Full Name' => 'Nom complet',
    'Home' => 'Accueil',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Identifiant ou mot de passe incorrect.',
    'Instructor' => 'Instructeur',
    'Instructors' => 'Les instructeurs',
    'Login' => 'S\'identifier',
    'Logout' => 'Connectez - Out',
    'Name' => 'Prénom',
    'Next' => 'Prochain',
    'Please Sign In' => 'S\'il vous plaît Se connecter',
    'Remember Me' => 'Souviens-toi de moi',
    'Save' => 'Sauvegarder',
    'Schedules' => 'Des horaires',
    'Semester' => 'Semestre',
    'Semesters' => 'Semestres',
    'Status' => 'Statut',
    'Students' => 'Élèves',
    'The requested page does not exist.' => 'La page demandée n\'existe pas.',
    'Time Slot' => 'Créneau horaire',
    'Time Slots' => 'Tranches de temps',
    'Title' => 'Titre',
    'Total Courses Registered' => 'Total Cours enregistrés',
    'Type' => 'Type',
    'Update' => 'Mettre à jour',
    'Update Course Field: {nameAttribute}' => 'Mise à jour cours du domaine: {nameAttribute}',
    'Update Course: {nameAttribute}' => 'Mise à jour du cours: {nameAttribute}',
    'Update Instructor: {nameAttribute}' => 'Instructeur de mise à jour: {nameAttribute}',
    'Update Schedule: {nameAttribute}' => 'Mise à jour Calendrier: {nameAttribute}',
    'Update Semester: {nameAttribute}' => 'Mise à jour semestre: {nameAttribute}',
    'Update Student: {nameAttribute}' => 'Mise à jour des étudiants: {nameAttribute}',
    'Update Time Slot: {nameAttribute}' => 'Mise à jour Créneau: {nameAttribute}',
    'Updated At' => 'Mise à jour à',
    'Updated By' => 'Mis à jour par',
    'User ID' => 'Identifiant d\'utilisateur',
];
