<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'Are you sure you want to delete this item?' => '',
    'All Registered Courses'=>'جميع الدورات مسجل',
    'Are you sure you want to delete this item?'=>'هل أنت متأكد أنك تريد حذف هذا البند؟',
    'Back'=>'الى الخلف',
    'Bio'=>'السيرة الذاتية',
    'Class'=>'صف دراسي',
    'Code'=>'الشفرة',
    'Course'=>'دورة',
    'Course Field'=>'الميدان بالطبع',
    'Course Fields'=>'الحقول بالطبع',
    'Courses'=>'الدورات',
    'Create Course'=>'إنشاء ملعب',
    'Create Course Field'=>'إنشاء حقل دورة',
    'Create Instructor'=>'إنشاء مدرس',
    'Create Schedule'=>'إنشاء جدول',
    'Create Semester'=>'إنشاء الفصل الدراسي',
    'Create Student'=>'إنشاء طالب',
    'Create Time Slot'=>'خلق فتحة الوقت',
    'Created At'=>'أنشئت في',
    'Created By'=>'صنع من قبل',
    'Dashboard'=>'لوحة القيادة',
    'Delete'=>'حذف',
    'Enter email'=>'أدخل البريد الإلكتروني',
    'Enter password'=>'أدخل كلمة المرور',
    'Field'=>'حقل',
    'Full Name'=>'الاسم الكامل',
    'Home'=>'الصفحة الرئيسية',
    'ID'=>'هوية شخصية',
    'Instructor'=>'مدرب',
    'Instructors'=>'المدربين',
    'Login'=>'تسجيل الدخول',
    'Logout'=>'الخروج',
    'Name'=>'اسم',
    'Next'=>'التالى',
    'Save'=>'حفظ',
    'Schedules'=>'جداول',
    'Semester'=>'نصف السنة',
    'Semesters'=>'فصول دراسية',
    'Status'=>'الحالة',
    'Students'=>'الطلاب',
    'The requested page does not exist.'=>'الصفحة المطلوبة غير موجودة.',
    'Time Slot'=>'فسحة زمنية',
    'Time Slots'=>'فتحات الوقت',
    'Title'=>'عنوان',
    'Total Courses Registered'=>'مسجل مجموع الدورات',
    'Type'=>'اكتب',
    'Update'=>'تحديث',
    'Update Course Field: {nameAttribute}'=>'تحديث الميدان ملعب: {nameAttribute}',
    'Update Course: {nameAttribute}'=>'دورة التحديث: {nameAttribute}',
    'Update Instructor: {nameAttribute}'=>'تحديث مدرس: {nameAttribute}',
    'Update Schedule: {nameAttribute}'=>'الجدول الزمني تحديث: {nameAttribute}',
    'Update Semester: {nameAttribute}'=>'تحديث الفصل الدراسي: {nameAttribute}',
    'Update Student: {nameAttribute}'=>'تحديث طالب: {nameAttribute}',
    'Update Time Slot: {nameAttribute}'=>'فتحة تحديث الوقت: {nameAttribute}',
    'Updated At'=>'تم التحديث في',
    'Updated By'=>'تم التحديث بواسطة',
    'User ID'=>'معرف المستخدم',
    'Remember Me'=>'تذكرنى',
    'Please Sign In'=>'الرجاء تسجيل الدخول',
    'Incorrect username or password.'=>'اسم المستخدم أو كلمة المرور غير صحيحة.',
    'Course Code'=>'رمز المقرر',
    'View Details'=>'عرض التفاصيل',
];
