<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'Are you sure you want to delete this item?' => '',
    'Course Code' => 'コースコード',
    'View Details' => '詳細を見る',
    'All Registered Courses' => '登録されているすべてのコース',
    'Are you sure you want to delete this item?' => 'あなたは、この項目を削除してもよろしいですか？',
    'Back' => 'バック',
    'Bio' => 'バイオ',
    'Class' => 'クラス',
    'Code' => 'コード',
    'Course' => 'コース',
    'Course Field' => 'コースフィールド',
    'Course Fields' => 'コースのフィールド',
    'Courses' => 'コース',
    'Create Course' => 'コースを作成します。',
    'Create Course Field' => 'コースのフィールドを作成します。',
    'Create Instructor' => 'インストラクターを作成します。',
    'Create Schedule' => 'スケジュールを作成します。',
    'Create Semester' => '学期を作成します。',
    'Create Student' => '学生を作成します。',
    'Create Time Slot' => 'タイムスロットを作成します。',
    'Created At' => 'で作成されました',
    'Created By' => 'によって作成された',
    'Dashboard' => '計器盤',
    'Delete' => '削除',
    'Enter email' => 'メールアドレスを入力して',
    'Enter password' => 'パスワードを入力する',
    'Field' => 'フィールド',
    'Full Name' => 'フルネーム',
    'Home' => '家',
    'ID' => 'ID',
    'Incorrect username or password.' => 'ユーザーネームまたはパスワードが違います。',
    'Instructor' => 'インストラクター',
    'Instructors' => 'インストラクター',
    'Login' => 'ログイン',
    'Logout' => 'ログアウト',
    'Name' => '名',
    'Next' => '次',
    'Please Sign In' => 'サインインしてください',
    'Remember Me' => '私を覚えてますか',
    'Save' => 'セーブ',
    'Schedules' => 'スケジュール',
    'Semester' => '学期',
    'Semesters' => '学期',
    'Status' => '状態',
    'Students' => '学生の',
    'The requested page does not exist.' => '要求されたページは存在しません。',
    'Time Slot' => 'タイムスロット',
    'Time Slots' => 'タイムスロット',
    'Title' => 'タイトル',
    'Total Courses Registered' => '登録総数コース',
    'Type' => 'タイプ',
    'Update' => '更新',
    'Update Course Field: {nameAttribute}' => 'アップデートコースフィールド',
    'Update Course: {nameAttribute}' => 'コースを更新します。',
    'Update Instructor: {nameAttribute}' => '更新インストラクター',
    'Update Schedule: {nameAttribute}' => '更新スケジュール',
    'Update Semester: {nameAttribute}' => 'アップデート学期',
    'Update Student: {nameAttribute}' => 'アップデート学生',
    'Update Time Slot: {nameAttribute}' => '更新時間スロット',
    'Updated At' => 'で更新',
    'Updated By' => 'によって更新',
    'User ID' => 'ユーザーID',
];
