<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'Are you sure you want to delete this item?' => '',
    'All Registered Courses' => '',
    'Are you sure you want to delete this item?' => '',
    'Back' => '',
    'Bio' => '',
    'Class' => '',
    'Code' => '',
    'Course' => '',
    'Course Code' => '',
    'Course Field' => '',
    'Course Field ID' => '',
    'Course Fields' => '',
    'Courses' => '',
    'Create Course' => '',
    'Create Course Field' => '',
    'Create Instructor' => '',
    'Create Schedule' => '',
    'Create Semester' => '',
    'Create Student' => '',
    'Create Time Slot' => '',
    'Created At' => '',
    'Created By' => '',
    'Dashboard' => '',
    'Delete' => '',
    'Enter email' => '',
    'Enter password' => '',
    'Field' => '',
    'Full Name' => '',
    'Home' => '',
    'ID' => '',
    'Incorrect username or password.' => '',
    'Instructor' => '',
    'Instructor ID' => '',
    'Instructors' => '',
    'Login' => '',
    'Logout' => '',
    'Name' => '',
    'Next' => '',
    'Please Sign In' => '',
    'Remember Me' => '',
    'Save' => '',
    'Schedules' => '',
    'Semester' => '',
    'Semester ID' => '',
    'Semesters' => '',
    'Status' => '',
    'Students' => '',
    'The requested page does not exist.' => '',
    'Time Slot' => '',
    'Time Slots' => '',
    'Title' => '',
    'Total Courses Registered' => '',
    'Type' => '',
    'Update' => '',
    'Update Course Field: {nameAttribute}' => '',
    'Update Course: {nameAttribute}' => '',
    'Update Instructor: {nameAttribute}' => '',
    'Update Schedule: {nameAttribute}' => '',
    'Update Semester: {nameAttribute}' => '',
    'Update Student: {nameAttribute}' => '',
    'Update Time Slot: {nameAttribute}' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'View Details' => '',
];
